### ISSUE TITLE
Colors are set for the wrong calendar

### ISSUE THREAD

**Issue by it25fg** [pascalfree/calendar-color#1]
When there are more calendars than fit on one screen height, colors intended for calendars beyond the first screen height go to the wrong calendars. Example: I have 9 calendars, the "calendar color" widget shows 8 of them. To set the color for the last one, I scroll up until it is visible (note: the 9th calendar of the whole list is now the 8th on the currently displayed screen). Then I choose a color and confirm it. -> The color gets set at the 8th calendar of the whole list.

My system is Android 4.4.2 on an LG L40.
Using Calendar Color 0.1 as shipped by F-Droid.

**Comment by pascalfree** [comment]
Hi it25fg
I could reproduce the error. The first changes worked fine, then the affected calendar seemed to be a random one, I think it didn't even follow the rule you described.

Thanks for reporting. I'll have a look at it.

**Comment by pascalfree** [comment]
Fixed it. New version will be in fdroid soon.
