### ISSUE TITLE
colors reset after reloading calendar

### ISSUE THREAD

**Issue by hoschi-it** [pascalfree/calendar-color#3]
Android 4.4, (using selhosted synched calendars)
Setting colors first changes the color of events in the calendar app (even when testing multiple calendar apps).
After creating a new event, the colors reset to default, even showing this in calendar-color.
(Thanks a lot for providing us with this app!!!)

**Comment by pascalfree** [comment]
Hi Hoschi-it

What software are you using for the selfhosted calendars? Some calendar providers like owncloud let you change the calendar colors in their application. 
In that case the changes made with this app will be overwritten by the setting on the server, as soon as you sync again.

**Comment by hoschi-it** [comment]
Hi pascalfree,

I use davical for sync. I don't know about it having a feature like this.
Apart from that, it works perfectly on another device (Android 5.1, same sync server and settings, forgot to say that), so I think it must have something to do with the version.
Thanks for your fast reply!

**Comment by hoschi-it** [comment]
I'm sorry, it was just a false alarm.
I had to deactivate the "choose colors" function in the sync adaptors settings.
Sorry for contacting you!
Have a nice morning/day/evening/night.

**Comment by pascalfree** [comment]
Okay, thanks. for reporting. Whats the sync adaptor you are using? This information might help others with the same problem.

**Comment by hoschi-it** [comment]
The app I made the setting in is DAVdroid.
That's the app I'm using for synchronization.

**Comment by pascalfree** [comment]
Thanks, I didn't know about this option in the app.
