### ISSUE TITLE
Possible feature: widget 

### ISSUE THREAD

**Issue by anthony-vivek** [pascalfree/calendar-color#6]
I would recommend adding a widget so that users can access their calendars from the homescreen of their device.
How I came up with this recommendation: I came up with this recommendation by analyzing the reviews from a popular
competitor app: DigiCal Calendar Agenda. By extracting topics from this app along with the words that described the 
topics, I noticed that a feature that users seem to love is having a widget. With users saying things such as
:"The widget is beyond compare & it has all the features I could think of & more" and
"Both the widget and the app are attractive and easy to configure.". 
Why I came up with this recommendation: Given that users seem to really like having 
the widget functionality and my topic modelling analysis has the word 'widget' to describe 5 of the 10 topics that I
extracted, I think adding a widget to the app would greatly benefit users.

**Comment by pascalfree** [comment]
This app does not display calendars. It just changes their color.
