### ISSUE TITLE
Possible feature: sync to Outlook 

### ISSUE THREAD

**Issue by anthony-vivek** [pascalfree/calendar-color#7]
I would recommend adding a feature that allows users to sync their calendars with OutLook.
How I came up with this recommendation: by analyzing the reviews from a similar app: aCalendar+ Calendar & Tasks.
I extracted the reviews from this app and applied topic modeling. Many of the topics had the word "sync" and I 
decided to look into how this word was being used in reviews.
Why I came up with this recommendation: So I looked into what people liked about the app's syncing feature and it seems 
like they really like that the app allows them to sync their calendars with OutLook. Users left reviews saying
: "Love this app. Syncs with Google calendar & my Outlook calendar." and
Love this app. The only one I have found that can sync my outlook work calendar and my 
multiple Google calendars all into one." Therefore I think it would add great value to Calendar Color if it allowed
users to sync their calendars to OutLook.

**Comment by pascalfree** [comment]
This app does not sync calendars. It just changes their color setting.
